spring.application.name=ServerCart
# ???? ???????
server.port=8080
# ????????? ????? (?????? ??? Yandex)
spring.mail.host=smtp.rambler.ru
spring.mail.port=465
spring.mail.username=louisecaezgf0@rambler.ru
spring.mail.password=wvmtxkzmS!1805
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

spring.datasource.url=jdbc:postgresql://localhost:5432/SyncCart
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update